@host = http://localhost:5035

### Hent kaffemeny
GET {{host}}/menu
Accept: application/json

### Opprett bestilling
POST {{host}}/orders
Content-Type: application/json

{
  "coffeeId": "00000000-0000-0000-0000-000000000001",
  "size": "MEDIUM",
  "milkType": "OAT",
  "extraShot": true,
  "customerName": "Ola Nordmann",
  "quantity": 2
}

### Hent spesifikk bestilling
GET {{host}}/orders/00000000-0000-0000-0000-000000000000
Accept: application/json

### Se den genererte OpenAPI-spesifikasjonen (åpne i browser)
# {{host}}/openapi/v1.json

### Åpne Scalar UI (åpne i browser)
# {{host}}/scalar/v1
